/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hp1180br
 */
public class Telalogin extends javax.swing.JFrame {
    
    //JFrame jframe = new JFrame("Sistema de gestão Acadêica");
    
    /**
     * Creates new form Telalogin
     */
    public Telalogin() {
        initComponents();
        seticon();

    }
    
     
    public final void seticon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/iconApp.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloSistema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCampoUsuario1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButtonSairTelaPrincipal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonEntrar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCampoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTituloSistema.setBackground(new java.awt.Color(0, 102, 51));
        jLabelTituloSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloSistema.setText("SISACAD - SISTEMA ACADÊMICO");
        getContentPane().add(jLabelTituloSistema);
        jLabelTituloSistema.setBounds(0, 0, 480, 50);

        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 180, 50, 30);

        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 140, 50, 30);
        getContentPane().add(jTextFieldCampoUsuario1);
        jTextFieldCampoUsuario1.setBounds(250, 140, 160, 28);

        jCheckBox1.setText("Mantenha-me Conectado");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(250, 210, 170, 20);

        jButtonSairTelaPrincipal.setText("Sair");
        jButtonSairTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairTelaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairTelaPrincipal);
        jButtonSairTelaPrincipal.setBounds(290, 270, 70, 23);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 50);

        jButtonEntrar1.setText("Entrar");
        jButtonEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar1);
        jButtonEntrar1.setBounds(290, 240, 70, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siscAcadem.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, 100, 200, 170);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Desenvolvido por rsoft.com Ltda, - Todos os direitos reservados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 324, 480, 30);

        jTextFieldCampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoSenha);
        jTextFieldCampoSenha.setBounds(250, 180, 160, 30);

        setSize(new java.awt.Dimension(494, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrar1ActionPerformed
        if(!jTextFieldCampoUsuario1.getText().equals("admin")|| !jTextFieldCampoSenha.getText().equals("12345")){
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválida!!!");
        } else{
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEntrar1ActionPerformed

    private void jButtonSairTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairTelaPrincipalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairTelaPrincipalActionPerformed

    private void jTextFieldCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Telalogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar1;
    private javax.swing.JButton jButtonSairTelaPrincipal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTituloSistema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTextFieldCampoSenha;
    private javax.swing.JTextField jTextFieldCampoUsuario1;
    // End of variables declaration//GEN-END:variables
}
