/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;

/**
 *
 * @author hp1180br
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        seticon();
    }
    
        public final void seticon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/iconApp.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameInternalframe = new javax.swing.JInternalFrame();
        jPanelInterna = new javax.swing.JPanel();
        jButtonCadAluno = new javax.swing.JButton();
        jButtonCadDiretor1 = new javax.swing.JButton();
        jButtonCadProfessor1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadDiretor = new javax.swing.JMenuItem();
        jMenuItemCadProfessor = new javax.swing.JMenuItem();
        jMenuItemCadAluno = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameInternalframe.setTitle("Bem-vindo");
        jInternalFrameInternalframe.setVisible(true);
        jInternalFrameInternalframe.getContentPane().setLayout(null);

        jPanelInterna.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterna.setLayout(null);

        jButtonCadAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadAluno.setText("Aluno");
        jButtonCadAluno.setToolTipText("Cadastro Aluno");
        jButtonCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAlunoActionPerformed(evt);
            }
        });
        jPanelInterna.add(jButtonCadAluno);
        jButtonCadAluno.setBounds(260, 50, 100, 100);

        jButtonCadDiretor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadDiretor1.setText("Diretor");
        jButtonCadDiretor1.setToolTipText("Cadastro Diretor");
        jButtonCadDiretor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadDiretor1ActionPerformed(evt);
            }
        });
        jPanelInterna.add(jButtonCadDiretor1);
        jButtonCadDiretor1.setBounds(40, 50, 100, 100);

        jButtonCadProfessor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadProfessor1.setText("Professor");
        jButtonCadProfessor1.setToolTipText("Cadastro Professor");
        jButtonCadProfessor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProfessor1ActionPerformed(evt);
            }
        });
        jPanelInterna.add(jButtonCadProfessor1);
        jButtonCadProfessor1.setBounds(150, 50, 100, 100);

        jInternalFrameInternalframe.getContentPane().add(jPanelInterna);
        jPanelInterna.setBounds(-10, 40, 750, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento");
        jInternalFrameInternalframe.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 162, 15);

        getContentPane().add(jInternalFrameInternalframe);
        jInternalFrameInternalframe.setBounds(20, 140, 750, 280);

        jMenuInicio.setText("Início");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemSair);

        jMenuBar1.add(jMenuInicio);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadDiretor.setText("Diretor");
        jMenuItemCadDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadDiretorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadDiretor);

        jMenuItemCadProfessor.setText("Professor");
        jMenuItemCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProfessorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadProfessor);

        jMenuItemCadAluno.setText("Aluno");
        jMenuItemCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadAlunoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadAluno);

        jMenuBar1.add(jMenuCadastro);

        jMenu1.setText("Ferramentas");

        jMenuItem2.setText("Tela Bem-Vindo");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(810, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadDiretorActionPerformed

    }//GEN-LAST:event_jMenuItemCadDiretorActionPerformed

    private void jMenuItemCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadAlunoActionPerformed

    private void jMenuItemCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadProfessorActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);        
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //getContentPane().setLayout(null);        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadAlunoActionPerformed

    private void jButtonCadDiretor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadDiretor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadDiretor1ActionPerformed

    private void jButtonCadProfessor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProfessor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadProfessor1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadAluno;
    private javax.swing.JButton jButtonCadDiretor1;
    private javax.swing.JButton jButtonCadProfessor1;
    private javax.swing.JInternalFrame jInternalFrameInternalframe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCadAluno;
    private javax.swing.JMenuItem jMenuItemCadDiretor;
    private javax.swing.JMenuItem jMenuItemCadProfessor;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanelInterna;
    // End of variables declaration//GEN-END:variables
}
